Global:
  infer_imgs: "api/uploads/00bfebf9.jpeg"
  embed_model_dir: "../models/embedding"

  batch_size: 1
  use_gpu: True

# # PPLCNEtV2-512
# RecPreProcess:
#   transform_ops:
#     - ResizeImage:
#         size: [224, 224]
#         return_numpy: False
#         interpolation: bilinear
#         backend: cv2
#     - NormalizeImage:
#         scale: 1.0/255.0
#         mean: [0.485, 0.456, 0.406]
#         std: [0.229, 0.224, 0.225]
#         order: hwc
#     - ToCHWImage:

# RecPostProcess: null

# # icartoon-2048
# RecPreProcess:
#   transform_ops:
#     - ResizeImage:
#         size: [224, 224]
#         return_numpy: False
#         interpolation: bilinear
#         backend: cv2
#     - NormalizeImage:
#         scale: 0.00392157
#         mean: [0.485, 0.456, 0.406]
#         std: [0.229, 0.224, 0.225]
#         order: ''
#     - ToCHWImage:

# RecPostProcess: null

# RecPreProcess:
#   transform_ops:
#     - ResizeImage:
#         size: [224, 224]
#     - NormalizeImage:
#         scale: 0.00392157
#         mean: [0.485, 0.456, 0.406]
#         std: [0.229, 0.224, 0.225]
#         order: ''
#     - ToCHWImage:

# RecPostProcess: null

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

RecPostProcess: null